/*
  Reachability of the screens that write Debrief Logbook entries.

  The logbook save path was correct and the logbook stayed empty anyway: on a
  390px phone the drill pane started 2,298px down a 5,030px procedure page with
  nothing above it to say a drill existed, the ?drill=1 deep link that scrolls
  to it was never generated by any screen, and the empty state named the path in
  prose without linking to it. A working writer nobody can reach is a broken
  feature, so these assertions guard the wiring, not the arithmetic.
*/
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => fs.readFileSync(path.join(root, p), "utf8");
/* Scan code, not prose: logbook.js explains in a comment which screens call
   addLogbookEntry, and a naive scan counted the comment as a call site. */
const code = (p) => read(p).replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:])\/\/.*$/gm, "$1");

const procedures = read("app/js/screens/procedures.js");
const logbook = read("app/js/screens/logbook.js");
const training = read("app/js/screens/training.js");
const cockpit = read("app/js/screens/cockpitscreens.js");
const appjs = read("app/app.js");

/* ------------------------------------------------------- who writes entries */

test("exactly three screens write logbook entries, and each has a route", () => {
  const writers = ["app/js/screens/procedures.js", "app/js/screens/training.js", "app/js/screens/cockpitscreens.js"];
  const found = fs.readdirSync(path.join(root, "app/js/screens"))
    .filter((f) => f.endsWith(".js"))
    .filter((f) => /Store\.addLogbookEntry/.test(code("app/js/screens/" + f)))
    .map((f) => "app/js/screens/" + f)
    .sort();
  assert.deepEqual(found, writers.slice().sort(),
    "a screen started or stopped writing logbook entries — update the empty state in logbook.js to match");
});

/* --------------------------------------------- the procedure drill entry point */

test("the procedure screen offers the drill above the checklist, not only below it", () => {
  assert.match(procedures, /class: "btn primary block drill-jump"/,
    "the top-of-procedure drill button is gone");
  const ctaAt = procedures.indexOf("drill-jump");
  const paneAt = procedures.indexOf("nodes.push(drillPane(");
  assert.ok(ctaAt > -1 && paneAt > -1 && ctaAt < paneAt,
    "the drill button must be added to nodes before the drill pane, so it renders above it");
});

test("the drill button appears under the same condition as the drill pane", () => {
  // Both must be gated on hasDrill: a button that scrolls to a pane that was
  // never built is worse than no button.
  assert.match(procedures, /const hasDrill = lines\.memoryItems\.length > 0 \|\| lines\.checklistItems\.length > 0;/);
  assert.match(procedures, /if \(hasDrill\) \{/);
  assert.match(procedures, /if \(hasDrill\) nodes\.push\(drillPane\(|if \(hasDrill\) \{[\s\S]*?\}\s*\n\s*if \(savedEdit\)/);
});

test("jumping to the drill does not fight the scroll with a focus", () => {
  // focus() scrolls the element into view on its own, which lands the pane part
  // way down the viewport and undoes the smooth scroll. Measured on desktop:
  // 497px instead of 0 before preventScroll, 72px after.
  const focusCalls = procedures.match(/\.focus\((.*?)\)/g) || [];
  assert.ok(focusCalls.length >= 2, "expected the CTA and autoStart focus calls");
  focusCalls.forEach((call) => {
    assert.match(call, /preventScroll: true/,
      "every focus() in the drill jump path must pass { preventScroll: true }: " + call);
  });
});

test("autoStart is read, not just accepted", () => {
  // It was passed to drillPane for two phases and never used; the scroll it was
  // supposed to trigger lived in procedureDetail instead.
  assert.match(procedures, /autoStart: ctx\.query\.get\("drill"\) === "1"/, "the ?drill=1 link stopped being wired");
  assert.match(procedures, /if \(opts\.autoStart\) \{/, "drillPane ignores autoStart again");
  assert.doesNotMatch(procedures, /ctx\.query\.get\("drill"\) === "1"\) setTimeout/,
    "the duplicate scroll in procedureDetail is back");
});

/* ----------------------------------------------------- the logbook empty state */

test("the empty logbook links to every screen that can fill it", () => {
  assert.match(logbook, /function emptyState\(\)/);
  ["#/qrh", "#/quizzes", "#/live"].forEach((href) => {
    assert.ok(logbook.includes('href: "' + href + '"'),
      "the empty logbook must link to " + href);
  });
  assert.doesNotMatch(logbook, /No attempts yet\. Complete a procedure drill \(PROCS/,
    "the dead-end prose empty state is back");
});

test("every empty-state link resolves to a registered route", () => {
  const hrefs = (logbook.match(/href: "#\/[a-z-]+"/g) || []).map((m) => m.slice(8, -1));
  assert.ok(hrefs.length >= 3);
  hrefs.forEach((href) => {
    const route = href.replace(/^#/, "");
    assert.ok(appjs.includes('route("' + route + '"'),
      href + " is not a registered route in app/app.js");
  });
});

test("the filter bar is not rendered over an empty logbook", () => {
  // Search, five sort chips, three selects and the overrides toggle filter
  // nothing when there are no rows, and on a 390px phone they pushed the empty
  // state — the only useful thing on the screen — below the fold.
  const render = logbook.slice(logbook.indexOf("function render()"), logbook.indexOf("function emptyState()"));
  const emptyAt = render.indexOf("emptyState()");
  const barAt = render.indexOf("filterBar(render");
  assert.ok(emptyAt > -1 && barAt > -1);
  assert.ok(emptyAt < barAt, "the empty-state early return must come before the filter bar is appended");
});

test("the empty state does not promise entries from screens that never write one", () => {
  // CRM Drill ends with speech and no logbook entry; listing it here would be
  // the same defect in reverse.
  assert.ok(!/crm-drill/.test(logbook), "the empty state links to CRM Drill, which writes no entry");
  assert.doesNotMatch(read("app/js/screens/crmdrill.js"), /addLogbookEntry/,
    "CRM Drill now writes entries — add it to the logbook empty state");
});

/* --------------------------------------------------------------- the writers */

test("the quiz and scenario writers are still wired", () => {
  assert.match(training, /Store\.addLogbookEntry\(Q\.quizResultToLogbookEntry\(result\)\)/);
  assert.match(cockpit, /onComplete: function \(entry\) \{ Store\.addLogbookEntry\(entry\);/);
});
